app = "quirrel-api"

[env]
  ENABLE_USAGE_METERING = "true"

[[services]]
  internal_port = 9181
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000