# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI

on:
  push:
    paths:
      - api/**
  pull_request:
    paths:
      - api/**

defaults:
  run:
    working-directory: api

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:12

    services:
      redis:
        image: redis
        # wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      REDIS_URL: redis://redis:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm test -- --forceExit
  
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          path: api
          username: skn0tt
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: quirrel-dev/quirrel/quirrel
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true