name: CI

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 14, 15]

    services:
      redis:
        image: redis
        # wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    env:
      REDIS_URL: redis://localhost:6379
      DISABLE_TELEMETRY: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - if: ${{ matrix.node-version == 14 }}
      uses: microsoft/playwright-github-action@v1
    - run: npm i -g npm@7
    - run: npm ci
    - run: npm run build
    - run: npm test -- --coverage
    - if: ${{ matrix.node-version == 14 }}
      name: Coveralls Quirrel
      uses: coverallsapp/github-action@master
      with:
        flag-name: quirrel
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
        parallel: true
    - if: ${{ matrix.node-version == 14 }}
      run: npm ci
      working-directory: development-ui
    - if: ${{ matrix.node-version == 14 }}
      run: npm run test:ci
      working-directory: development-ui
    - if: ${{ matrix.node-version == 14 }}
      name: Coveralls Dev UI
      uses: coverallsapp/github-action@master
      with:
        flag-name: development-ui
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-path: development-ui
        path-to-lcov: development-ui/coverage/lcov.info
        parallel: true
    - if: ${{ matrix.node-version == 14 }}
      name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: skn0tt
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: quirrel-dev/quirrel
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_PROJECT_PATH: quirrel
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
